# Generated by Django 3.2.8 on 2022-08-11 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='imagen',
            field=models.ImageField(default='user_default.png', upload_to='usuario'),
        ),
    ]
