# Generated by Django 3.2.8 on 2022-08-11 22:28

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0004_alter_noticia_activo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='texto',
            field=ckeditor.fields.RichTextField(default=2),
            preserve_default=False,
        ),
    ]
