# Generated by Django 3.2.8 on 2022-08-15 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0005_alter_noticia_texto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Titulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
            ],
        ),
        migrations.RemoveField(
            model_name='noticia',
            name='titulo',
        ),
        migrations.AddField(
            model_name='noticia',
            name='titlo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='noticias.titulo'),
        ),
    ]
