# Generated by Django 3.2.8 on 2022-08-15 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0006_auto_20220815_1855'),
    ]

    operations = [
        migrations.RenameField(
            model_name='noticia',
            old_name='titlo',
            new_name='titulo',
        ),
    ]
