# Generated by Django 3.2.8 on 2022-08-15 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0007_rename_titlo_noticia_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='titulo',
            field=models.CharField(max_length=250),
        ),
        migrations.DeleteModel(
            name='Titulo',
        ),
    ]
