# Generated by Django 3.2.8 on 2022-08-15 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_auto_20220814_0812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='imagen',
            field=models.ImageField(default='usuario/user_default.png', upload_to='usuario'),
        ),
    ]
