# Generated by Django 3.2.8 on 2022-08-11 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0002_noticia_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='activo',
            field=models.BooleanField(null=True),
        ),
    ]
