# Generated by Django 3.2.8 on 2022-08-11 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0003_noticia_activo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
